### ISSUE TITLE
feat: resolve the root level of target schema to usable fields for CLI

### ISSUE THREAD

**Issue by Oran-Dan** [impierce/impierce-mapper#12]
### Description

Differing from actual json instances, json schemas have a lot of extra information and simply reading out all key-values won't attain much of a usable serde_json::Value. Our desire is to have a Value from which we can easily present the user the required fields, the optional fields and their conditions.
To attain a usable Value to work with at the root level we must apply custom code.

### Motivation

Necessary for properly loading target fields for "missing fields" and "optional fields".

### To-do List

- [x] Trim metadata: $schema, $id, title, description, type, addition
- [x] Resolve properties and defs into the Value
- [x] Add entered values into a new Value, this also means fetching values from here for display in CLI even though keys are fetched from the (resolved) schema.
- [x] Logical constructs: resolve into separate schemas, add layer on root level notifying user of the logical construct and listing the schema's in the construct.
- [x] Add "Additional property field" functionality.
- [x] Duplicate keys between schemas within a logical construct will display the same Value, as only one Value is entered into the final Value instance
- [x] Resolve "refs and "defs"
